### ISSUE TITLE
1.18.2 - A deadlock when smelting using furnace in backpack (Recreated Crash)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Luis-st/Forge-XBackpack#3]
XBackpack-1.18.2-2.8.jar

Please fix for 1.18.2 (This is not a feature request this is simple maintaining.)

- Honestly the simplest way to fix it is disable extra functions and would take no real effort on your part.

- I am only using this mod for spelunking so its nice to have the space to drop things.

A Deadlock means no log no crash and server goes into stasis.

**Comment by Luis-St** [comment]
I will look for it since I fixed the bug in a 1.19 release, so it's just a backport.

I will inform you when the problem is fixed

**Comment by Luis-St** [comment]
I am unable to reproduce the problem.

Could you give me a list of all your mods you have installed?
And please explain what exactly you have done.

**Comment by P3rf3ctXZer0** [comment]
So I added Xbackpack to Vault Hunters pack and anytime I smelt raw copper in the backpack furnace it Deadlocks the server. This however has no problem working as storage. Also using Minecraft furnaces or Furnaces outside of the xbackpack have no problems at all so even if you cannot recreate the issue I am certain the issue would cease just by making a version that disables furnace. (Crafting table works fine and I never tested the other modules.)

**Comment by Luis-St** [comment]
Just so I understand, the bug occurs on a server, not in single player?

**Comment by P3rf3ctXZer0** [comment]
No it happens in both environments

**Comment by P3rf3ctXZer0** [comment]
If you want the exact modpack https://www.dropbox.com/s/k5v1fi5wd64cvpm/Vault%20Hunters%203rd%20Edition%20Alt%20By%20Zer0-Update-6H-ABZ-08.zip?dl=0

**Comment by P3rf3ctXZer0** [comment]
Since I modified VH3rd for personal use it felt like bad taste to distribute it. (Also I cannot seem to contact the dev.)

**Comment by Luis-St** [comment]
Could you please post the debug.log from the client and if you are playing on a server, the server debug.log.
Even if there is no error.

**Comment by P3rf3ctXZer0** [comment]
Sure I would have to recreate it again though ... um ... let me go ahead then (My Partner is Going to Hate me.) (My other luck is it is yet another Euclidian bug.)

**Comment by P3rf3ctXZer0** [comment]
Leave this open - I am sure it will it will rear its ugly head and I will close it in 7 days if it does not happen again (I promise.)

**Comment by P3rf3ctXZer0** [comment]
@Luis-St This is legit all the info I can provide.

https://gist.github.com/P3rf3ctXZer0/c783112383316ec3e86d0fcd609f7d96

**Comment by Luis-St** [comment]
Please post the debug.log, note on CurseForge you need to enable the debug.log in the settings.

**Comment by P3rf3ctXZer0** [comment]
I did post it.
 https://gist.github.com/P3rf3ctXZer0/c783112383316ec3e86d0fcd609f7d96#file-debug-log

**Comment by P3rf3ctXZer0** [comment]
I wish the file spacing was better on Gist.

**Comment by Luis-St** [comment]
Please post also the launcher log
